name: Foodgram_workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Tests_project_flake8:
    name: Project testing with Flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r backend/foodgram_project/requirements.txt
    - name: Tests with flake8
      run: | 
        python -m flake8
  Build_foodgram_image_and_push_to_Docker_Hub:
    name: Push backend container to Docker Hub
    runs-on: ubuntu-latest
    needs: Tests_project_flake8
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          context: ./backend/foodgram_project/
          push: true
          tags: amaterasq/foodgram_backend:latest

  Deploy:
    name: Push backend container to server
    runs-on: ubuntu-latest
    needs: Build_foodgram_image_and_push_to_Docker_Hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            sudo docker pull amaterasq/foodgram_backend:latest
            cd infra/
            sudo docker-compose stop
            sudo docker-compose up --always-recreate-deps -d
